language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: UA1wwxtwlWOb7glP37H4zWmcd/NNToRtV33EoD5zutf4BF+nCs6TdDAcKCQEvJz6r0KQswwgzPWALbNfn3dFDyB01jXIqrznCAeJfyz8dI38lxDj7fEdUstFeKXwkizYB13w7lsIu2NXJQXS2Nr4Dot5sKFFV7JrPiXzfoKUcSM=

repos:
  XRAN: http://yihui.name/xran

before_install:
  - "curl -L https://yihui.name/xran/.gitconfig -o ~/.gitconfig"

after_success:
  - "(curl -L https://yihui.name/xran/r-xran | bash)"
