language: c

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: "UA1wwxtwlWOb7glP37H4zWmcd/NNToRtV33EoD5zutf4BF+nCs6TdDAcKCQEvJz6r0KQswwgzPWALbNfn3dFDyB01jXIqrznCAeJfyz8dI38lxDj7fEdUstFeKXwkizYB13w7lsIu2NXJQXS2Nr4Dot5sKFFV7JrPiXzfoKUcSM="

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-cran-boot
    - r-cran-class
    - r-cran-cluster
    - r-cran-codetools
    - r-cran-foreign
    - r-cran-kernsmooth
    - r-cran-lattice
    - r-cran-mass
    - r-cran-matrix
    - r-cran-mgcv
    - r-cran-nlme
    - r-cran-nnet
    - r-cran-rodbc
    - r-cran-rpart
    - r-cran-spatial
    - r-cran-survival

install:
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
